include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - .dart_tool/**
    - .idea/**
    - .vscode/**
    - build/**
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - test/**_mock.dart

  errors:
    # General error handling and best practices
    # You can set an (issue to error, warning, or info).
    invalid_annotation_target: error
    invalid_override: error
    missing_return: error
    missing_required_param: error
    non_constant_identifier_names: error
    nullable_type_in_catch_clause: error
    invalid_assignment: error
    dead_code: error
    unnecessary_cast: error
    ambiguous_import: error
    avoid_print: warning
    await_only_futures: error

  # Strong mode type checking and error-prone code analysis
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true

linter:
  rules:
    # Code Style
    always_declare_return_types: true
    annotate_overrides: true
    avoid_print: true
    prefer_final_fields: true
    unnecessary_string_escapes: true

    # Best Practices
    avoid_classes_with_only_static_members: true
    avoid_returning_null_for_future: true
    avoid_void_async: true
    unnecessary_null_checks: true
    invariant_booleans: true
    prefer_is_empty: true
    prefer_is_not_empty: true

    # Performance
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_unnecessary_containers: true
    prefer_final_locals: true
    avoid_function_literals_in_foreach_calls: true

    # Readability
    curly_braces_in_flow_control_structures: true
    prefer_single_quotes: true
    prefer_interpolation_to_compose_strings: true
    avoid_as: true
    prefer_spread_collections: true

    # Errors and Exceptions
    avoid_catches_without_on_clauses: true
    empty_catches: false

    # Flutter-specific Rules
    avoid_redundant_argument_values: true
    use_key_in_widget_constructors: true
    prefer_mixin: true
    prefer_const_constructors_in_immutables: true

    # Type System Rules
    always_specify_types: true

    # Miscellaneous Rules
    no_leading_underscores_for_local_identifiers: true
    prefer_function_declarations_over_variables: true
    unnecessary_lambdas: true

    # Pedantic Rules (Optional)
    always_put_control_body_on_new_line: true
